export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_PARAGRAPH_TO_POST = "ADD_PARAGRAPH_TO_POST";
export const ADD_IMAGE_TO_POST = "ADD_IMAGE_TO_POST";
export const ADD_HEADER_TO_POST = "ADD_HEADER_TO_POST";